import { motion } from "framer-motion";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import {
  FileText,
  CheckCircle,
  Smartphone,
  DollarSign,
  RefreshCcw,
  Handshake,
  ShieldCheck,
} from "lucide-react";

const TermosCondicoes = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-12"
          >
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-6">
              <FileText className="w-8 h-8 text-primary" />
            </div>
            <h1 className="text-3xl md:text-4xl font-display font-bold text-foreground mb-4">
              Terms and Conditions – Fazedores Angola
            </h1>
            <p className="text-muted-foreground">
              These Terms govern the use of the platform and establish the rights
              and duties of clients and doers.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="space-y-10"
          >
            {/* 1. Acceptance */}
            <section className="bg-card rounded-[2rem] p-6 md:p-8 border border-border shadow-lg">
              <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-primary" />
                1. Acceptance and Purpose
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Fazedores Angola is a **technological connection ecosystem**. By using our services, you agree that the platform acts as a facilitator of visibility and management, and is not a direct party to the financial transaction of the service provided.
              </p>
            </section>

            {/* 2. Direct Payment Flow */}
            <section className="bg-card rounded-[2rem] p-6 md:p-8 border border-border shadow-lg">
              <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-primary" />
                2. Payments and Transactions
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                To ensure agility in the local market, the financial flow works as follows:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-3 ml-4">
                <li>
                  <span className="font-semibold text-foreground">Direct Payment:</span> The full value of the service execution is paid by the client **directly to the Doer**, through the methods agreed between both (Cash, Express, or Transfer).
                </li>
                <li>
                  <span className="font-semibold text-foreground">Doer's Responsibility:</span> The doer is responsible for honoring the commission or platform usage fee generated by the service intermediation.
                </li>
                <li>
                  <span className="font-semibold text-foreground">Financial Independence:</span> Fazedores Angola does not retain, hold, or take responsibility for amounts paid by clients to providers.
                </li>
              </ul>
            </section>

            {/* 3. Marketing and Visibility */}
            <section className="bg-card rounded-[2rem] p-6 md:p-8 border border-border shadow-lg">
              <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <ShieldCheck className="w-5 h-5 text-primary" />
                3. Marketing and Growth Plans
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                The doer invests in their digital presence through our plans:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-3 ml-4">
                <li>
                  <span className="font-semibold text-foreground">Subscription:</span> The payment made to the platform refers strictly to technology services, marketing, content editing, and management tools.
                </li>
                <li>
                  <span className="font-semibold text-foreground">Image Use:</span> By submitting media for editing, the doer guarantees authorship of the work. Fazedores Angola reserves the right to use this content to promote the professional's talent on our networks.
                </li>
              </ul>
            </section>

            {/* 4. Mediation */}
            <section className="bg-card rounded-[2rem] p-6 md:p-8 border border-border shadow-lg">
              <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <RefreshCcw className="w-5 h-5 text-primary" />
                4. Mediation and Conduct
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Although payment is direct, the platform ensures quality:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-3 ml-4">
                <li>
                  Doers with a history of improper charges or unfinished services will be removed from the ecosystem.
                </li>
                <li>
                  The team conducts audits in case of complaints to verify whether the agreement between the parties was fulfilled.
                </li>
              </ul>
            </section>

            {/* 5. Contact */}
            <section className="bg-card rounded-[2rem] p-6 md:p-8 border border-border shadow-lg">
              <h2 className="text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <Handshake className="w-5 h-5 text-primary" />
                5. Applicable Law and Support
              </h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                In compliance with the laws of the Republic of Angola. For questions about plan billing or conduct:
              </p>
              <div className="p-4 bg-muted/50 rounded-2xl border border-border">
                <p className="text-foreground font-medium">contacto@fazedoresangola.com</p>
                <p className="text-sm text-muted-foreground mt-1">Luanda, Angola</p>
              </div>
            </section>
          </motion.div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TermosCondicoes;
